name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.3.0
        with:
          version: 5.15.0
      - name: Run cmake
        run: cmake .
      - name: Run build
        run: cmake --build .
      - name: Run tests
        run: ctest

